# Generated by Django 3.2.9 on 2021-11-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_superuser',
        ),
    ]
