# Generated by Django 3.2.9 on 2021-11-15 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entertainment', '0002_auto_20211114_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
            preserve_default=False,
        ),
    ]
